# Default values for workflow-police-robocat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nx/workflow_police/robocat
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# comment the line below to set default INFO level
# logLevel: DEBUG

# jira login api token
jiraPassword:

# robocat config file
robocatConfig: |
  jira:
    url: https://networkoptix.atlassian.net/
    login: service@networkoptix.com
    password: {{ .Values.jiraPassword }}
    timeout: 10
    retries: 1
    project_keys:
      - VMS
      - MOBILE
      - CB
      - SQ
      - NXLIB

  repo:
    path: /var/workflow_robocat/nx
    url: "git@gitlab.lan.hdw.mx:dev/nx.git"

  # Configuration for checking open-source part of the project.
  open_source_check_rule:
    approve_rules:
      -
        patterns:
          - open_candidate/vms/client/.+
          - open_candidate/cloud/.+
        approvers:
          - sivanov
          - mshevchenko
      -
        patterns:
          - open/.+
          - open_candidate/build_utils/.+
          - open_candidate/cmake/.+
          - open_candidate/dependencies/.+
          - open_candidate/vms/libs/.+
          - open_candidate/libs/.+
        approvers:
          - ptolstov
          - mshevchenko

  # Configuration for processing Issues from related Projects.
  process_related_merge_requests_rule:
    rules:
      -
        trigger_title_pattern: 'VMS-28944: Updates webadmin to [a-z0-9]+'
        issue_keys_pattern: 'Changelog: (?P<issue_keys>(?: *,? *[A-Z][A-Z0-9_]+-\d+)+)'
        related_projects:
            - CLOUD
        action: finalize

  # Configuration for checking changes in Nx Submodules.
  nx_submodule_check_rule:
    nx_submodule_dirs:
      - conan_profiles
      - build_utils/nx_submodule
      - open_candidate/artifacts/analytics_icons
      - open_candidate/conan_profiles

persistence:
  existingClaim: '{{ .Release.Name }}'
  hostPath: /srv/workflow_robocat-{{ .Release.Name }}
  size: 1G
  # Clean data volume on start: remove last_check file, repository.
  wipeData: false

# gitlab api token
gitlabToken:

# gitlab project id
gitlabProjectId: 2

# Merge requests poll rate
gitlabMrPollRate: 30

# Address of Graylog service to send GELF logs to
gelfServer: graylog.lan.hdw.mx:12201

# robocat gitlab config file
gitlabConfig: |
  [global]
  default = nx_gitlab
  ssl_verify = true
  timeout = 20

  [nx_gitlab]
  url = https://gitlab.lan.hdw.mx/
  private_token = {{ .Values.gitlabToken }}
  api_version = 4

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector:
  workflow-police: deploy

tolerations: []

affinity: {}
