jira:
    url: https://networkoptix.atlassian.net/
    login: service@networkoptix.com
    password: PASSWORD_HERE
    timeout: 10
    retries: 1
    project_keys:
        - VMS
        - MOBILE
        - CB
        - SQ
        - NXLIB

    custom_project_configs:
        NXLIB:
            statuses:
            - review: IN REVIEW
            - progress: IN PROGRESS
            - closed: DONE
            - open: To Do
            transitions:
            - workflow_failure: back to development

repo:
    path: /var/workflow_robocat/nx
    url: "git@gitlab.nxvms.dev:dev/nx.git"

# Configuration for checking open-source part of the project.
open_source_check_rule:
    approve_rules:
        -
            patterns:
                - open_candidate/vms/client/.+
                - open_candidate/cloud/.+
            approvers:
                - sivanov
                - mshevchenko
        -
            patterns:
                - open/.+
                - open_candidate/build_utils/.+
                - open_candidate/cmake/.+
                - open_candidate/dependencies/.+
                - open_candidate/vms/libs/.+
                - open_candidate/libs/.+
            approvers:
                - ptolstov
                - mshevchenko

# Configuration for processing Issues from the related Projects.
process_related_merge_requests_rule:
    rules:
        -
            trigger_title_pattern: 'VMS-28944: Updates webadmin to [a-z0-9]+'
            issue_keys_pattern: 'Changelog: (?P<issue_keys>(?: *,? *[A-Z][A-Z0-9_]+-\d+)+)'
            related_projects:
                - CLOUD
            action: finalize

# Configuration for checking changes in Nx Submodules.
nx_submodule_check_rule:
    nx_submodule_dirs:
        - conan_profiles
        - build_utils/nx_submodule
        - open_candidate/artifacts/analytics_icons
        - open_candidate/conan_profiles
