jira:
    url: https://networkoptix.atlassian.net/
    login: service@networkoptix.com
    password: PASSWORD_HERE
    timeout: 10
    retries: 1
    project_keys:
        - VMS
        - MOBILE
        - CB
        - SQ
        - NXLIB

repo:
    path: /var/workflow_robocat/testrepo
    url: "git@gitlab.nxvms.dev:dev-functests/testrepo.git"

# Configuration for "open source check" rule.
open_source_check_rule:
    approve_rules:
        # The order of patterns is important: to find the set of the most appropriate approvers,
        # these patterns are checked in the order listed here, so the most specific patterns must go
        # first, followed by the least specific ones.
        -
            patterns:
                - open_candidate/vms/client/.+
                - open_candidate/cloud/.+
                - open/vms/client/.+
                - open/cloud/.+
            approvers:
                - workflow-robocat
        -
            patterns:
                - open/.+
                - open_candidate/.+
            approvers:
                - ptolstov

# Configuration for checking changes in Nx Submodules.
nx_submodule_check_rule:
    nx_submodule_dirs:
        - conan_profiles
        - build_utils/nx_submodule
        - open/artifacts/analytics_icons
        - open/conan_profiles
