jira:
    url: https://networkoptix.atlassian.net/
    login: service@networkoptix.com
    password: PASSWORD_HERE
    timeout: 10
    retries: 1

repo:
    path: /var/workflow_robocat/testrepo
    url: "git@gitlab.lan.hdw.mx:dev-functests/testrepo.git"

# Configuration for "open source check" rule.
open_source_check_rule:
    approve_rules:
        -
            patterns:
                - open_candidate/vms/client/.+
                - open_candidate/cloud/.+
            approvers:
                - workflow-robocat
        -
            patterns:
                - open/.+
                - open_candidate/build_utils/.+
                - open_candidate/cmake/.+
                - open_candidate/dependencies/.+
                - open_candidate/vms/libs/.+
                - open_candidate/libs/.+
            approvers:
                - ptolstov

# Configuration for checking changes in Nx Submodules.
nx_submodule_check_rule:
    nx_submodule_dirs:
        - conan_profiles
        - build_utils/nx_submodule
        - open_candidate/artifacts/analytics_icons
        - open_candidate/conan_profiles
