jira:
    url: https://networkoptix.atlassian.net/
    login: service@networkoptix.com
    password: PASSWORD_HERE
    timeout: 5
    retries: 1

repo:
    path: /var/workflow_robocat/testrepo
    url: "git@gitlab.lan.hdw.mx:dev-functests/testrepo.git"

# Configuration for "open source check" rule.
open_source_checkers_map:
    "open*":
        - ptolstov
        - mshevchenko
    "open_candidate/**/*.cpp":
        - gdm
