jira:
    url: https://networkoptix.atlassian.net/
    login: service@networkoptix.com
    password: PASSWORD_HERE
    timeout: 10
    retries: 1
    project_keys:
        - VMS
        - MOBILE
        - CB
        - SQ

repo:
    path: /tmp/nx
    url: "git@gitlab.lan.hdw.mx:dev/nx.git"
polling_period_min: 5
last_check_file: /tmp/last_check
