jira:
    url: https://networkoptix.atlassian.net/
    login: service@networkoptix.com
    password: PASSWORD_HERE
    timeout: 10
    retries: 1

standard_projects: &standard_projects
    - VMS
    - MOBILE
    - CB
    - SQ
    - NXLIB

vms_repo: &vms_repo
    path: /tmp/nx
    url: "git@gitlab.nxvms.dev:dev/nx.git"

checkers:
    ignore_by_project:
        projects:
            - *standard_projects
            - CLOUD
    ignore_by_label:
        projects:
            - *standard_projects
            - CLOUD
    ignore_by_type:
        projects: *standard_projects
    ignore_fixed:
        projects:
            - *standard_projects
            - CLOUD
    ignore_by_version:
        projects:
            - CLOUD
        relevant_versions:
            - master
            - "5.0"
    wrong_version:
        projects: *standard_projects
    missing_branch:
        repo: *vms_repo
        projects: *standard_projects
    missing_issue_commit:
        repo: *vms_repo
        projects: *standard_projects
    missing_commit_to_master:
        repo: *vms_repo
        projects: *standard_projects
    no_related_commit:
        repo: *vms_repo
        related_project_id: 2
        projects:
            - CLOUD

polling_period_min: 5
last_check_file: /tmp/last_check

gitlab:
    url: https://gitlab.nxvms.dev/
    private_token: <PRIVATE_TOKEN>
    api_version: "4"
    timeout: 20
